POSTGRES_USER: ENC[AES256_GCM,data:RsxnS33QTQ==,iv:oB7a7lOA0zjpcNL2KfzaloNqLO7QRmHZd3p94YK5SKE=,tag:lxUOcj1IqzvilZBsN+PEEg==,type:str]
POSTGRES_PASSWORD: ENC[AES256_GCM,data:t4Bl1kHhrNIsibaJ0h3zl8M=,iv:OEvJIzLlpNXrFsDEvpSKHp87QbHSnjvCFxIjLJDSMAM=,tag:LtoG0wDi2jaAfEgzDdSZ2g==,type:str]
SECRET_KEY: ENC[AES256_GCM,data:aCuLpvKI0LRmxE4R/hWg,iv:Fvn8XNWeTHYlHaRNElFPwXOEv6u7bU2TcczajVTtPd4=,tag:6zdsu36yXuykTnuEqD1kYQ==,type:str]
DATABASE_URL: ENC[AES256_GCM,data:osHsjxOqODIDXgRVIFrB1pOoCuBEug6x6NO7B9xYKg2U1OfnQx9xGi2laQ4lOUU7wHNQcMXr7iE=,iv:6tu3uN3gLwUetmgkY8AhlERs3zluU24dh72eiJ2J0PE=,tag:HCLJM5XwczvEIzZK0rTg3A==,type:str]
sops:
    age:
        - recipient: age1wut8wa3qrklq9n06nvp5sygjcmt43e0yw4xs0ewugy8skv7gqqgqfwssrp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbUpaSmduUzB3WmZuSVNn
            V2RhblIzOTlmMjdlOUFPcDA0ajJrekRyVUQ4CmpiR1BHWEtraFhQTE84NjJCYUNo
            eUNMaUt0dFNkRDgyMCt3NldkcW1ET1EKLS0tIEpKbmxQVnZlU1dYSE1veldUNFJ0
            dk94dkMvRHlSbm5XTUdaelFlS05YTkUKplw26k58RGycYjDJXQexmKeGm23RQioG
            t6IORKtqT9mN+D3BZwttlnP8/nz6E0LUtGQZZuSLP5V1QBjL5dU5rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-16T19:57:31Z"
    mac: ENC[AES256_GCM,data:QBgU49TJH43lugGrr5k7HOKAMCMX3FYcHW3g5KVvollDAGroLGGMxKX35PkQtJXhbt1owbvXdoLIy7f9ANLhoszrP4u8s0f9El/HXd6FmhxcvFpHv/9BckNVUjbcUyu17F3CFquoRt7IhhBQ+kQ1JpkvRZ+zOcCkWAqeDnUa3MM=,iv:87NZjAFLaHSdd9SbRH8hbsSKx1f2X39J1w1tLpK+tTk=,tag:D7C1JEg0TiKDkMFtdDDwBQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
