apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.POSTGRES_PASSWORD | quote }}
  SECRET_KEY: {{ .Values.SECRET_KEY | quote }}
  DATABASE_URL: {{ .Values.DATABASE_URL | quote }}
